final/SDEV_Final/SDEV_Final/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage ),
    path('about/', views.about ),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
    path('inventory/', views.inventory ),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/SDEV_Final/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name="list"),
    path('<slug:slug>', views.post_page, name="page"),
]

final/SDEV_Final/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
]

mysite/urls.py
from django.urls import path, include
from django.contrib import admin

from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('', include('blog.urls')),
]

final/SDEV_Final/posts/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField( )
    slug = models.SlugField( )
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)

    def __str__(self):
        return self.title
    

final/SDEV_Final/users/models.py
from django.db import models

# Create your models here.

final/SDEV_Final/SDEV_Final/views.py
# from django.http import HttpResponse
from django.shortcuts import render 

def homepage(request):
    # return HttpResponse("Hello World! I'm Home.")
    return render(request, 'home.html')

def about(request):
    # return HttpResponse("My About Page.")
    return render(request, 'about.html')
def inventory(request):
    return render(request, 'inventory.html')

final/SDEV_Final/posts/views.py
from django.shortcuts import render
from .models import Post

# Create your views here.


def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts': posts})


def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post': post})

final/SDEV_Final/users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register_view(request):
    form = UserCreationForm( )
    return render(request, "users/register.html", {" form ": form })

final/SDEV_Final/posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{% block title  %}
    {{ post.title }}
{% endblock  %}

{% block content%}
    <section>
        <img
            class="banner" 
            src="{{ post.banner.url }}"
            alt="{{ post.title }}"
        />
        <h1>{{ post.title }}</h1>
        <p>{{ post.body }}</p>
    </section>
{% endblock %}

final/SDEV_Final/posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <section>
    <h1>Click Name For Vehicle Picture</h1>

    {% for post in posts %}
        <article class="post">
            <h2>
                <a href="{%  url 'posts:page' slug=post.slug %}">
                <p> {{ post.title }} <p>
                </a>
            </h2>
            <p>{{ post.body }}</p>
        </article>
    {% endfor %}
</section>
{% endblock %}

final/SDEV_Final/templates/about.html
{% extends 'layout.html' %}

{% block title  %}
    About
{% endblock  %}

{% block content%}
    <h1>About Us</h1>
    <p>417 E Main St</p>
    <p>Brownsburg, IN 46112</p>
    <p>(317) 286-7147</p>
    <p><a href="/">Home</a> page.</p>
{% endblock %}

final/SDEV_Final/templates/home.html
{% extends 'layout.html' %}

{% block title  %}
    Home
{% endblock  %}

{% block content%}
<h1>The Goat Import</h1>
<p> Check out our <a href = "{% url 'posts:list' %}">Inventory</a>! </p>
{% endblock %}

final/SDEV_Final/templates/inventory.html
{% extends 'layout.html' %}

{% block title  %}
    Inventory
{% endblock  %}

{% block content%}
    <h1>About</h1>
    <p>This is Group Two Final Project in SDEV202 </p>
    <p>Minh Tong</p>
    <p>Richard Clark Elijah</p>
    <p><a href="/">Home</a> page.</p>
{% endblock %}

final/SDEV_Final/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="/">The Goat Import</a> |
        <a href="/about">About Us</a> |
        <a href="{% url 'posts:list' %}">Cars</a> 
    </nav>
    <main>
        {% block content%}
        {% endblock %}
    </main>
</body>
</html>

final/SDEV_Final/users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a New User
{% endblock %}

{% block content %}
    <form class="form-with-validation" action="/users/register/" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit">Submit</button>
    </form>
{% endblock %}